# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-23 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userId',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
